{  
   "Asia": {
      "Eastern Asia":[
         "name":"China",
         "name":"Hong Kong",
         "name":"Japan",
         "name":"Macao",
         "name":"Mongolia",
         "name":"North Korea",
         "name":"South Korea",
         "name":"Taiwan"
      ],
      "South-Eastern Asia": [
         "name":"Brunei Darussalam",
         "name":"Cambodia",
         "name":"Indonesia",
         "name":"Laos",
         "name":"Malaysia",
         "name":"Myanmar",
         "name":"Philippines",
         "name":"Singapore",
         "name":"Thailand",
         "name":"Timor-Leste",
         "name":"Vietnam"
      ],
      "Southern Asia": [
         "name":"Afghanistan",
         "name":"Bangladesh",
         "name":"Bhutan",
         "name":"India",
         "name":"Iran",
         "name":"Maldives",
         "name":"Nepal",
         "name":"Pakistan",
         "name":"Sri Lanka"
      ],
      "Western Asia": [
         "name":"Armenia",
         "name":"Azerbaijan",
         "name":"Bahrain",
         "name":"Georgia",
         "name":"Iraq",
         "name":"Israel",
         "name":"Jordan",
         "name":"Kuwait",
         "name":"Lebanon",
         "name":"Oman",
         "name":"Palestine",
         "name":"Qatar",
         "name":"Saudi Arabia",
         "name":"Syria",
         "name":"Turkey",
         "name":"United Arab Emirates",
         "name":"Yemen"
      ],
      "Central Asia": [
         "name":"Kazakhstan",
         "name":"Kyrgyzstan",
         "name":"Tajikistan",
         "name":"Turkmenistan",
         "name":"Uzbekistan"
      ]
   },
   "Africa": {
      "Northern Africa": [
         "name":"Algeria",
         "name":"Egypt",
         "name":"Libya",
         "name":"Morocco",
         "name":"Sudan",
         "name":"Western Sahara"
      ],
      "Southern Africa": [
         "name":"Botswana",
         "name":"French Southern Territories",
         "name":"Lesotho",
         "name":"Namibia",
         "name":"South Africa",
         "name":"Swaziland"
      ],
      "Middle Africa": [
         "name":"Angola",
         "name":"Cameroon",
         "name":"Central African Republic",
         "name":"Chad",
         "name":"Congo",
         "name":"Congo (Democratic Republic of the)",
         "name":"Equatorial Guinea",
         "name":"Gabon",
         "name":"South Sudan"
      ],
      "Eastern Africa": [
         "name":"British Indian Ocean Territory",
         "name":"Burundi",
         "name":"Comoros",
         "name":"Djibouti",
         "name":"Eritrea",
         "name":"Ethiopia",
         "name":"Kenya",
         "name":"Madagascar",
         "name":"Malawi",
         "name":"Mauritius",
         "name":"Mayotte",
         "name":"Mozambique",
         "name":"Réunion",
         "name":"Rwanda",
         "name":"Seychelles",
         "name":"Somalia",
         "name":"Tanzania",
         "name":"Uganda",
         "name":"Zambia",
         "name":"Zimbabwe"
      ],
      "Western Africa": [
         "name":"Benin",
         "name":"Burkina Faso",
         "name":"Cabo Verde",
         "name":"Gambia",
         "name":"Ghana",
         "name":"Guinea",
         "name":"Guinea-Bissau",
         "name":"Côte d'Ivoire",
         "name":"Liberia",
         "name":"Mali",
         "name":"Mauritania",
         "name":"Niger",
         "name":"Nigeria",
         "name":"Saint Helena, Ascension and Tristan da Cunha",
         "name":"Senegal",
         "name":"Sierra Leone",
         "name":"Togo"
      ]
   },
   "Americas": {
      "Caribbean": [
         "name":"Anguilla",
         "name":"Antigua and Barbuda",
         "name":"Aruba",
         "name":"Bahamas",
         "name":"Barbados",
         "name":"Bonaire, Sint Eustatius and Saba",
         "name":"Virgin Islands (British)",
         "name":"Virgin Islands (U.S.)",
         "name":"Cayman Islands",
         "name":"Cuba",
         "name":"Curaçao",
         "name":"Dominica",
         "name":"Dominican Republic",
         "name":"Grenada",
         "name":"Guadeloupe",
         "name":"Haiti",
         "name":"Jamaica",
         "name":"Martinique",
         "name":"Montserrat",
         "name":"Puerto Rico",
         "name":"Saint Barthélemy",
         "name":"Saint Kitts and Nevis",
         "name":"Saint Lucia",
         "name":"Saint Martin (French part)",
         "name":"Saint Vincent and the Grenadines",
         "name":"Sint Maarten (Dutch part)",
         "name":"Trinidad and Tobago",
         "name":"Turks and Caicos Islands"
      ],
      "South America": [
         "name":"Argentina",
         "name":"Bolivia",
         "name":"Chile",
         "name":"Colombia",
         "name":"Ecuador",
         "name":"Falkland Islands",
         "name":"French Guiana",
         "name":"Guyana",
         "name":"Paraguay",
         "name":"Peru",
         "name":"South Georgia and the South Sandwich Islands",
         "name":"Suriname",
         "name":"Uruguay",
         "name":"Venezuela"
      ],
      "Central America": [
         "name":"Belize",
         "name":"Costa Rica",
         "name":"El Salvador",
         "name":"Guatemala",
         "name":"Honduras",
         "name":"Nicaragua",
         "name":"Panama"
      ],
      "North America": [
         "name":"Bermuda",
         "name":"United States Minor Outlying Islands",
         "name":"Canada",
         "name":"Greenland",
         "name":"Saint Pierre and Miquelon",
         "name":"United States of America"
      ]
   },
   "Europe": {
      "Northern Europe": [
         "Åland Islands",
         "name":"Denmark",
         "name":"Estonia",
         "name":"Faroe Islands",
         "name":"Finland",
         "name":"Guernsey",
         "name":"Iceland",
         "name":"Ireland",
         "name":"Isle of Man",
         "name":"Jersey",
         "name":"Latvia",
         "name":"Lithuania",
         "name":"Norway",
         "name":"Svalbard and Jan Mayen",
         "name":"Sweden",
         "name":"United Kingdom"
      ],
      "Southern Europe": [
         "name":"Albania",
         "name":"Andorra",
         "name":"Bosnia and Herzegovina",
         "name":"Croatia",
         "name":"Cyprus",
         "name":"Gibraltar",
         "name":"Greece",
         "name":"Holy See",
         "name":"Italy",
         "name":"Macedonia",
         "name":"Malta",
         "name":"Montenegro",
         "name":"Portugal",
         "name":"San Marino",
         "name":"Serbia",
         "name":"Slovenia",
         "name":"Spain"
      ],
      "Eastern Europe": [
         "name":"Belarus",
         "name":"Bulgaria",
         "name":"Czech Republic",
         "name":"Hungary",
         "name":"Moldova (Republic of)",
         "name":"Poland",
         "name":"Republic of Kosovo",
         "name":"Russian Federation",
         "name":"Slovakia",
         "name":"Ukraine"
      ],
      "Western Europe": [
         "name":"Austria",
         "name":"Belgium",
         "name":"France",
         "name":"Germany",
         "name":"Liechtenstein",
         "name":"Luxembourg",
         "name":"Monaco",
         "name":"Netherlands",
      ]
   },
   "Oceania": {
      "Australia and New Zealand": [
         "name":"Australia",
         "name":"Christmas Island",
         "name":"Cocos (Keeling) Islands",
         "name":"New Zealand",
         "name":"Norfolk Island"
      ],
      "Polynesia": [
         "name":"American Samoa",
         "name":"Cook Islands",
         "name":"French Polynesia",
         "name":"Niue",
         "name":"Pitcairn",
         "name":"Samoa",
         "name":"Tokelau",
         "name":"Tonga",
         "name":"Tuvalu",
         "name":"Wallis and Futuna"
      ],
      "Micronesia": [
         "name":"Guam",
         "name":"Kiribati",
         "name":"Marshall Islands",
         "name":"Micronesia (Federated States of)",
         "name":"Nauru",
         "name":"Northern Mariana Islands",
         "name":"Palau"
      ],
      "Melanesia": [
         "name":"Fiji",
         "name":"New Caledonia",
         "name":"Papua New Guinea",
         "name":"Solomon Islands",
         "name":"Vanuatu"
      ]
   }
}
